[[keyboard.bindings]]
chars = "\u0001%"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001\""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0001h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001z"
key = 36
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001p"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\f"
key = "Semicolon"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "Semicolon"
mode = "~Vi|~Search"
mods = "Command"
