-- For the records, I started with grapple.nvim, it's the successor of harpoon.
-- And I think ThePrimeagen started a great system for managing workflow,
-- but its successor is better in a lot of area for me.
-- I love the simplicity of the pop-up on Harpoon tho

-- local mark = require("harpoon.mark")
-- local ui = require("harpoon.ui")
--
-- vim.keymap.set('n', '<leader>e', function()
--   ui.toggle_quick_menu()
-- end)
--
-- vim.keymap.set('n', '<leader>s', function()
--   mark.add_file()
-- end)
--
-- vim.keymap.set('n', '<leader>j', function()
--   ui.nav_file(1)
-- end)
--
-- vim.keymap.set('n', '<leader>k', function()
--   ui.nav_file(2)
-- end)
--
-- vim.keymap.set('n', '<leader>l', function()
--   ui.nav_file(3)
-- end)
--
-- vim.keymap.set('n', '<leader>;', function()
--   ui.nav_file(4)
-- end)
--
-- vim.keymap.set('n', '<leader>h', function()
--   ui.nav_file(5)
-- end)
